language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install beautifulsoup4==4.4.0 coverage==3.7.1 coveralls

before_script:
  - bash fetch_data.sh

script:
  - coverage run tests.py

after_success:
  - coveralls
