#!/bin/bash
# Fetch data for testing the recipe_scraper package

curl -o recipe_scrapers/tests/test_data/101cookbooks.html  http://www.101cookbooks.com/archives/nikkis-healthy-cookies-recipe.html
curl -o recipe_scrapers/tests/test_data/allrecipes.html http://allrecipes.com/recipe/133948/four-cheese-margherita-pizza/ 
curl -o recipe_scrapers/tests/test_data/aspicyperspective.html https://www.aspicyperspective.com/banana-cream-pie-recipe/
curl -o recipe_scrapers/tests/test_data/backtoherroots.html http://wholefully.com/blue-cornbread/
curl -o recipe_scrapers/tests/test_data/bbc_food.html http://www.bbc.co.uk/food/recipes/baileysandchocolatec_72293
curl -o recipe_scrapers/tests/test_data/bbc_good_food.html http://www.bbcgoodfood.com/user/5632816/recipe/cookie-monster-cupcakes
curl -o recipe_scrapers/tests/test_data/biggirlssmallkitchen.html http://www.biggirlssmallkitchen.com/2011/11/cauliflower-soup-with-sharp-cheddar-and-thyme.html
curl -o recipe_scrapers/tests/test_data/bonappetit.html http://www.bonappetit.com/recipe/red-wine-braised-short-ribs
curl -o recipe_scrapers/tests/test_data/bunkycooks.html http://www.pratesiliving.com/the-best-three-cheese-lasagna-recipe/
curl -o recipe_scrapers/tests/test_data/chowhound.html http://www.chowhound.com/recipes/thanksgiving-turkey-cake-29029
curl -o recipe_scrapers/tests/test_data/closetcooking.html http://www.closetcooking.com/2012/11/bacon-wrapped-jalapeno-popper-stuffed.html
curl -o recipe_scrapers/tests/test_data/cookieandkate.html http://cookieandkate.com/2013/curried-cauliflower-soup/
curl -o recipe_scrapers/tests/test_data/cookincanuck.html http://www.cookincanuck.com/nutella-sea-salt-stuffed-sugar-cookie-recipe-oxo-baking-giveaway/
curl -o recipe_scrapers/tests/test_data/cookstr.html http://www.cookstr.com/Breakfast-Recipes/Mozzarella-Tomato-Basil-Frittata
curl -o recipe_scrapers/tests/test_data/delishhh.html http://carrotsandspice.com/2012/02/27/no-bake-nutella-cheesecake/
curl -o recipe_scrapers/tests/test_data/eatswellwithothers.html http://joanne-eatswellwithothers.com/2012/01/recipe-broccoli-basil-mac-and-cheese.html
curl -o recipe_scrapers/tests/test_data/elanaspantry.html http://elanaspantry.com/granola/
curl -o recipe_scrapers/tests/test_data/epicurious.html http://www.epicurious.com/recipes/food/views/poached-eggs-in-tomato-sauce-with-chickpeas-and-feta-368963
curl -o recipe_scrapers/tests/test_data/finedininglovers.html http://www.finedininglovers.com/recipes/first-course/zucchini-lasagna-raw-vegan-recipe/
curl -o recipe_scrapers/tests/test_data/foodandspice.html http://foodandspice.blogspot.com/2013/01/pumpkin-gingerbread-waffles.html
curl -o recipe_scrapers/tests/test_data/foodnetwork.html http://www.foodnetwork.com/recipes/bobby-flay/smoked-chile-scalloped-sweet-potatoes-recipe-1945789
curl -o recipe_scrapers/tests/test_data/foodrepublic.html http://www.foodrepublic.com/recipes/dutch-white-asparagus-recipe/
curl -o recipe_scrapers/tests/test_data/framedcooks.html http://www.framedcooks.com/2011/02/ham-and-egg-crepe-squares.html
curl -o recipe_scrapers/tests/test_data/giallozafferano.html http://ricette.giallozafferano.it/Bavarese-alle-fragole.html
curl -o recipe_scrapers/tests/test_data/healthy_delicious.html http://www.healthy-delicious.com/baked-chicken-and-spinach-flautas 
curl -o recipe_scrapers/tests/test_data/homesicktexan.html http://www.homesicktexan.com/2007/03/and-end-to-my-quest-flour-tortillas.html
curl -o recipe_scrapers/tests/test_data/jamieoliver.html http://www.jamieoliver.com/recipes/chocolate-recipes/bloomin-brilliant-brownies/ 
curl -o recipe_scrapers/tests/test_data/mybakingaddiction.html http://www.mybakingaddiction.com/cheesecake-in-a-jar-recipe/
curl -o recipe_scrapers/tests/test_data/naturellyella.html http://naturallyella.com/black-bean-tacos/
curl -o recipe_scrapers/tests/test_data/paninihappy.html http://paninihappy.com/grilled-mac-cheese-with-bbq-pulled-pork/
curl -o recipe_scrapers/tests/test_data/pastryaffair.html http://www.pastryaffair.com/blog/2011/7/14/butterbeer-cupcakes.html
curl -o recipe_scrapers/tests/test_data/pbs.html http://www.pbs.org/food/recipes/20-second-chocolate-cake/
curl -o recipe_scrapers/tests/test_data/pickypalate.html http://picky-palate.com/2013/03/27/cheesy-grown-up-spaghettios/
curl -o recipe_scrapers/tests/test_data/pillsburybaking.html http://www.pillsburybaking.com/recipes/peanut-butter-secrets-1595
curl -o recipe_scrapers/tests/test_data/realsimple.html http://www.realsimple.com/food-recipes/browse-all-recipes/pan-roasted-chicken-lemon-garlic-green-beans
curl -o recipe_scrapers/tests/test_data/seriouseats.html http://www.seriouseats.com/recipes/2011/04/homemade-horseradish-recipe.html
curl -o recipe_scrapers/tests/test_data/simpyrecipes.html http://www.simplyrecipes.com/recipes/cheesy_bread/
curl -o recipe_scrapers/tests/test_data/smittenkitchen.html http://smittenkitchen.com/2008/08/chocolate-peanut-butter-cake/
curl -o recipe_scrapers/tests/test_data/streamykitchen.html http://steamykitchen.com/271-vietnamese-pho-recipe.html
curl -o recipe_scrapers/tests/test_data/tasty_kitchen.html http://tastykitchen.com/recipes/breads/cheddar-and-garlic-scape-biscuits/
curl -o recipe_scrapers/tests/test_data/thepioneerwoman.html http://thepioneerwoman.com/cooking/patty-melts/
curl -o recipe_scrapers/tests/test_data/thevintagemixer.html http://www.thevintagemixer.com/cauliflower-pizza-crust-recipe/
curl -o recipe_scrapers/tests/test_data/twopeasandtheirpod.html http://www.twopeasandtheirpod.com/red-velvet-cheesecake-cookies/
curl -o recipe_scrapers/tests/test_data/whatsgabycooking.html http://whatsgabycooking.com/strawberry-basil-lemonade/
